version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
        XDEBUG_MODE: coverage
    command: bash -c "vendor/bin/phpunit --coverage-html /var/www/storage/test-coverage && vendor/bin/phpunit --coverage-text && tail -f /dev/null"

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
